decrypt:
    sops -d secrets.enc.yaml > docker-compose.override.yaml

encrypt:
    sops -e docker-compose.override.yaml > secrets.enc.yaml

clean:
    rm docker-compose.override.yaml

deploy-override:
    docker stack deploy --detach=false -c docker-compose.yaml -c docker-compose.override.yaml flipflow

deploy: decrypt deploy-override clean

destroy:
    docker stack rm flipflow
